name: Pipeline

on:
  push:
  pull_request:
    branches: [main]
  release: 
    types: [released]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,development]
      - name: Lint
        run: |
          black --check ./
          flake8 ./

  Test:
    needs: lint
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,development]
      - name: Setup
        run: helix install -v
      - name: Test
        run: |
          helix test system -v 2
          helix test unit -v 2
          helix test integration -v 2

  Deploy:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,development]
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
