name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,development]
      - name: Setup
        run: helix install -v
      - name: Test
        run: |
          helix test system -v 2
          helix test unit -v 2
          helix test integration -v 2
