name: Release

on:
  release: 
    types: [released]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,development]
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
